#!/usr/bin/env python3
"""Generate a Rust case-folding table from Unicode CaseFolding.txt.

Emits `casefold_tables.rs`:
  SIMPLE_FOLDS   — 1:1 (simple) case-folding mappings, sorted by source cp.
  EXPANDED_FOLDS — multi-codepoint full-fold expansions (documented; not used
                   by the char-at-a-time `fold_char` primitive).
"""
import sys

SRC = "tools/unicode/CaseFolding.txt"
OUT = "src/kernel/fs/unicode/casefold_tables.rs"

simple = {}   # src -> dst (single cp)
expanded = {} # src -> [cp...]  (multi-cp full fold)

for line in open(SRC, encoding="utf-8"):
    line = line.split("#", 1)[0].strip()
    if not line:
        continue
    fields = [f.strip() for f in line.split(";")]
    if len(fields) < 3:
        continue
    src = int(fields[0], 16)
    status = fields[1]
    dst = [int(x, 16) for x in fields[2].split()]
    if status == "S" or (status in ("C", "F") and len(dst) == 1):
        simple[src] = dst[0]
    elif len(dst) > 1:
        # Multi-cp full fold: record for documentation / future expansion.
        expanded[src] = dst

items = sorted(simple.items())

def esc(cp):
    return "\\u{%x}" % cp

lines = []
lines.append("//! src/kernel/fs/unicode/casefold_tables.rs")
lines.append("//! Generated by tools/unicode/gen_casefold_table.py — DO NOT EDIT.")
lines.append("//!")
lines.append("//! Source: Unicode CaseFolding.txt (Unicode %s)." % "15.0.0")
lines.append("//!")
lines.append("//! `SIMPLE_FOLDS` holds the 1:1 case-folding mappings (the Unicode")
lines.append("//! `S` column plus single-code-point `C`/`F` mappings) covering every")
lines.append("//! script with case.  It is sorted by source code point and binary-")
lines.append("//! searched by `fold_char`.")
lines.append("//!")
lines.append("//! `EXPANDED_FOLDS` records the multi-code-point full-fold expansions")
lines.append("//! (e.g. U+00DF `ß` -> `ss`).  A char-at-a-time comparison cannot")
lines.append("//! represent these, so they are retained here for documentation and")
lines.append("//! for a future full-folding comparison primitive.")
lines.append("")

lines.append("/// Sorted 1:1 case-folding mappings: `(source, folded)`.")
lines.append("pub static SIMPLE_FOLDS: &[(u32, u32)] = &[")
for src, dst in items:
    lines.append("    (0x%04X, 0x%04X), // U+%04X -> %s" % (src, dst, src, esc(dst)))
lines.append("];")
lines.append("")
lines.append("/// Multi-code-point full-fold expansions: `(source, folded)`.")
lines.append("/// Not used by `fold_char` (which folds a single char); kept for")
lines.append("/// reference and future expansion-aware comparison.")
lines.append("pub static EXPANDED_FOLDS: &[(u32, &[u32])] = &[")
for src, dst in sorted(expanded.items()):
    cps = ", ".join("0x%04X" % d for d in dst)
    lines.append("    (0x%04X, &[%s]), // U+%04X" % (src, cps, src))
lines.append("];")
lines.append("")

with open(OUT, "w", encoding="utf-8") as f:
    f.write("\n".join(lines) + "\n")

print("wrote %s: %d simple folds, %d expanded folds" % (OUT, len(items), len(expanded)))
